apiVersion: apps/v1
kind: Deployment
metadata:
  name: groq-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groq-app
  template:
    metadata:
      labels:
        app: groq-app
    spec:
      containers:
        - name: groq-app
          image: eyadahen/groq-app:latest
          imagePullPolicy: Always
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: groq-secret
                  key: api-key
          ports:
            - containerPort: 5000
          # 👇 Ajoute ceci
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
