apiVersion: apps/v1
kind: Deployment
metadata:
  name: groq-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groq-app
  template:
    metadata:
      labels:
        app: groq-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8010"  # ✅ Nouveau port Prometheus
    spec:
      containers:
        - name: groq-app
          image: eyadahen/groq-app:latest
          imagePullPolicy: Always
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: groq-secret
                  key: api-key
            - name: METRICS_PORT   # ✅ Ajoute ça
              value: "8010"
          ports:
            - containerPort: 8010  # ✅ Nouveau port
